name: 'test'
on: 
  workflow_dispatch
#  push:
#    paths:
#      - test-data/source/*

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
      - name: Run the action
        id: run
        uses: ./
        with:
          path: test-data/process
          source-language: sourcelang
          output-languages: testlang1, testlang2
      - name: Commit any changes
        uses: EndBug/add-and-commit@v9.0.0
        with:
          message: Auto-update loc files
          add: test-data/process
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
