name: 'build-test'
on: 
  workflow_dispatch
#  push:
#    paths:
#      - test-data/source/*

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v2
      - name: run
        uses: ./
        with:
          who-to-greet: World
      - name: output
        run: echo "The time was ${{ steps.run.outputs.time }}"