name: 'build-test'
on: 
  workflow_dispatch
#  push:
#    paths:
#      - test-data/source/*

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
      - name: Run the action
        id: run
        uses: ./
        with:
          who-to-greet: World
      - name: Get the output
        run: echo "The time was ${{ steps.hello.outputs.time }}"