name: 'test'
on: 
  workflow_dispatch
#  push:
#    paths:
#      - test-data/source/*

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
      - name: Run the action
        id: run
        uses: ./
        with:
          path: test-data
          source-language: source
          output-languages: output, output2
